FROM python:3.8.10-alpine3.14 as base

# For ansible
RUN apk add --no-cache openssh
RUN apk add --no-cache sudo
# https://github.com/gliderlabs/docker-alpine/issues/183#issuecomment-257014744
RUN apk add --no-cache openrc
# https://github.com/srvrco/getssl/issues/612
RUN apk add --no-cache coreutils
RUN echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN adduser -h /home/test -s /bin/sh -D test
RUN echo -n 'test:test' | chpasswd
RUN echo 'test 	ALL=(ALL)	NOPASSWD: ALL' >> /etc/sudoers
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN pip install requests
RUN pip install docker
#############

RUN mkdir /wip/
WORKDIR /wip/

COPY ./src/requirements.txt /wip/requirements.txt
RUN pip install -r /wip/requirements.txt

#https://stackoverflow.com/questions/18805073/docker-multiple-entrypoints
RUN apk add --no-cache supervisor 

COPY ./src/ /wip/
ENV FLASK_APP=server.py
#ENV FLASK_DEBUG=1

###########START NEW IMAGE: PRODUCTION ###################
FROM base as prod
#COPY ./supervisor.conf /wip/supervisor.conf
CMD supervisord -c /wip/supervisor.conf
#CMD flask run -h 0.0.0.0 -p 5000
